### ISSUE TITLE
Drills killing faction bases. #10th Issue!

### ISSUE THREAD

**Issue by BurninDreamer** [TFlippy/kag_territorycontrol#100]
As you already know if you did not live under a rock for your entire life which some of you did I'm sure,
drills destroy faction bases completely.

I'm sure that happens because a drill is hitting the faction base at the entire drills drilling radius.
So if you are hitting 1 faction block with the drill it doesn't destroy them anymore (I think).

The solution is simple enough:
Make so drills can hit only 1 faction base block at a time.

**Comment by Gingerbeard5773** [comment]
This is intentional probably from flippy. The hitters code in commonfactionbuilding.as at line 909 gives builders and drills 10x more damage to faction buildings.
