### ISSUE TITLE
Server crash via fragment mines.

### ISSUE THREAD

**Issue by BurninDreamer** [TFlippy/kag_territorycontrol#103]
There is a way to crash the server by spending 10k coins on fragment mines and stacking them in a spot,.

How to crash a server 101.  (KNOWLEDGE PROVIDED SOLELY FOR EDUCATION,)

1. Buy 10k worth of fragment mines.
2. Stack all of them in a single spot.
3. Throw something in that can trigger the mines. Example:
A cat, a chicken, a dead body, a player and something else I forgot.
4. Profit from crashing the server by getting a ban!

**Comment by Vam-Jam** [comment]
this isnt really a crash, you can do this with any item
