### ISSUE TITLE
Please enable drill for neuts again, it is a great thing to have.

### ISSUE THREAD

**Issue by asperger-sind** [TFlippy/kag_territorycontrol#123]
Oh hey Burnin new account!

So I think drills should be enabled for neuts starting from the builder class, but they cannot be used by the pleb neutrals (fresh spawned, 2 hp, deals no damage and can build taverny shit) and knights, archers and other sorts of potatoes.
So basically enable drills for neuts, but only engineers and builders can use them and maaaybe nerf the neutral drill damage to players by half or more.

ginger pls do im tired of digging dirt as a neut with a pikax!!1!!11!1111111!1

**Comment by asperger-sind** [comment]
also enable or fix the mithril drill, it's funi

**Comment by Vam-Jam** [comment]
Drill was disabled on neutrals to prevent them from constantly attacking buildings.

I plan to re-enable it, but neutrals will only be able to mine dirt, stone and ores, but anything else will result in extremely fast overheat.

**Comment by asperger-sind** [comment]
I agree on the idea, but I'd make it so neutrals can also mine wood blocks, platforms, stone blocks and maybe trees with normal speeds and no overheat since neutrals are mostly building their own neutral towns and structures if they are not trying to kill everybody, and sometimes you need to clean up a lot of map spawned houses, fix your wall since you messed up while building it and much more, and the drill there should shine at it's greatest. 

Yet I clearly understand that allowing stone blocks might allow for neutrals to break stone walls of a faction base, but nobody really builds bases out of stone nowadays so I guess it still is ok,

**Comment by asperger-sind** [comment]
"and no overheat" As in no overheat penalties.

**Comment by jammer312** [comment]
Alternatively make engineers the only class allowed to use them (regardless of team). Because knights were unable to use drills for a reason, and also it kinda fits the theme of engineer.

**Comment by jammer312** [comment]
> ginger pls do im tired of digging dirt as a neut with a pikax!!1!!11!1111111!1

Btw imagine not using dynamite for digging (again, regardless of team)

**Comment by asperger-sind** [comment]
Trust me, I would use dynamite for digging most of the time. If I had dynamite I would.
I think it's not exactly a good idea to make a bomb shop or that producer thing to break 20 dirt blocks.

**Comment by jammer312** [comment]
So making a bomb shop for that is not a good idea, but making a furnace and a mechanist shop is ok?

**Comment by asperger-sind** [comment]
Drills are great because:
Fits in your inventory at all times;
Reusable until you drop them in water for 10 seconds;
Cheap.
I liked drills as of in general because you don't need to make 30 billion of them or make them each time you need to get rid of dirt.

**Comment by Vam-Jam** [comment]
> 
> 
> Alternatively make engineers the only class allowed to use them (regardless of team). Because knights were unable to use drills for a reason, and also it kinda fits the theme of engineer.

Sounds like a good idea, much more consistent.
