### ISSUE TITLE
Fix hitting shops while using their UI

### ISSUE THREAD

**Issue by Gingerbeard5773** [TFlippy/kag_territorycontrol#134]
When inside the shop of another team's workshop- pressing buttons as a knight, bandit, etc will harm the workshop eventually breaking it.

**Comment by Vam-Jam** [comment]
This is a hard issue to fix.

The problem is that shops are client side, and clicking mouse is instantly sent to the server, along with that the server never knows when you have the menu open.

I have not looked into this engine side, but i believe there is no way to fix this script side. This needs a client side engine fix.

**Comment by asperger-sind** [comment]
Can't it just be
if activatedworkshop == 1
    damagetostructures = 0

**Comment by Vam-Jam** [comment]
No, server does not know when you have the menu opened, and does not properly fix the issue

**Comment by asperger-sind** [comment]
Sad, I assume this is practically inpossible to fix

**Comment by Vam-Jam** [comment]
Fixing script side will be a pain, it might be possible, but it's easier to fix it engine side. I'll look into this in the future.

**Comment by ghost** [comment]
the one thing that i know that disables sword without disabling left clicking for shops is sitting on a chair/cargo

**Comment by ghost** [comment]
demo:
https://user-images.githubusercontent.com/26771587/127952044-756e914a-caee-49ed-9621-647682146849.mp4

**Comment by ghost** [comment]
Seats.as has this:
```
void InitSeatAttachment(AttachmentPoint@ ap)
{
	if (ap !is null && ap.socket)
	{
		ap.offsetZ = -10.0f;
		ap.customData = 0;

		if (ap.name.find("PASSENGER") != -1)
		{
			//dont take mouse or actions so you can shoot
			ap.SetKeysToTake(key_left | key_right | key_up | key_down);
		}
		else if (ap.name == "DRIVER" || ap.name == "ROWER" || ap.name == "FLYER" || ap.name == "GUNNER" || ap.name == "MAG")
		{
			ap.SetKeysToTake(key_left | key_right | key_up | key_down | key_action1 | key_action2 | key_action3);
			ap.SetMouseTaken(true);
			
			if (ap.name == "DRIVER")
			{
				ap.controller = true;								// client-side movement
			}
		}
	}
}
```

and im guessing chair/cargo have a "PASSENGER" attachment point. so maybe doing something like that while you're overlapping with a shop could work?! i dunno

**Comment by ghost** [comment]
actually chair has `@$attachment_points                        = PILOT; 0; -5; 0; 1; 8;`
but cargo has `													PASSENGER; -12; 0; 0; 0; 8;
													PASSENGER; 4; 0; 0; 0; 8;
													PASSENGER; 20; 0; 0; 0; 8;`
so im confused why chair works.

**Comment by ghost** [comment]
actually i think it's {having your playerblob attached to something} + {that something not eating your key_action1 input}

so i dunno how that would help; maybe it's even an engine side thing that prevents mouse inputs from going to your playerblob when attached? 

could make a tiny chair-like attachment points to all shops to allow people to use shop without using sword; dunno

**Comment by xcs011** [comment]
Yeah but that would require them to physically enter the shop like a seat/vehicle, and make use of attachment points whose code is already engineside, and shitcode at that, it would probably just make more sense to fix it engine side normally.

**Comment by Vam-Jam** [comment]
> actually i think it's {having your playerblob attached to something} + {that something not eating your key_action1 input}
> 
> so i dunno how that would help; maybe it's even an engine side thing that prevents mouse inputs from going to your playerblob when attached?
> 
> could make a tiny chair-like attachment points to all shops to allow people to use shop without using sword; dunno

nice catch, i'll see if we can do anything useful with this. afaik we can move attachment points about in runtime, so we might able to make this 'hacky' workaround seamless

**Comment by Vam-Jam** [comment]
After spending an hour or two, I can't get a way to make it play nicely, the main issue is that attaching one blob to another requires server to run that code, which is hard to do currently since GUI is (mostly) client side since the addition of the new button func callback. And even if you could, server does not know when you exit the gui. Trying to sync the state's just makes it more messy/complex.

Ideally, sometime in the future I'll have client's not send updates about action_1 and so on when in a shop gui. Still requires an engine update.

**Comment by Gingerbeard5773** [comment]
Base kaggers can deal with this.
