### ISSUE TITLE
Fix E glitch (use button doesn't work)

### ISSUE THREAD

**Issue by Gingerbeard5773** [TFlippy/kag_territorycontrol#137]
The bug when a player cannot use any buttons when pressing the [E] key. It happens more frequently in TC but people have said that it has happened on other modded servers before (so this bug may be engine side). Though I do not doubt if it could be remedied through scripts.
This bug is notorious for being difficult to reproduce so it has gone unfixed for years despite seriously handicapping the player(s) who falls victim to it.
Here is what I understand about the bug-
1) Going next map fixes the bug in all cases.
2) Rejoining the server will not fix the bug.
3) Sometimes zooming in and out with the camera can help remedy the bug when the bug starts appearing. The bug usually appears more when using the closest zoom.
4) Players have said that it appears more in larger maps.
5) The bug almost never appears early game on a new map.

In my experience, I have noticed that pressing [E] when this bug is present will make interactable objects "glow" on and off, so the entire screen goes craze mode. Sometimes you can see buttons you would normally be able to use, except way off from the position the button is supposed to be at. 
There is one instance I know of where it was reproduceable in game; Players were playing in a faction and all teammates had the E glitch. Leaving the faction would remove the bug, but upon rejoining the faction, the glitch would return to the player.

That should be most of the information I know about it. If there is questions I will try to answer them with what I know.

**Comment by Gingerbeard5773** [comment]
On the map Goldy_TC_ThomsMega_Smoll it is possible to reproduce this bug relating to the train's behavior.

https://user-images.githubusercontent.com/68350259/116034276-41eac000-a620-11eb-9383-0ebde3abf302.mp4

When the train leaves the map the E glitch suddenly activates, however when the train returns to the map boundaries the glitch seems to turn off until the train leaves once again. The train was indeed a source, as when I destroyed it, the loop stopped.

**Comment by Vam-Jam** [comment]
Going to close this. I have made a PR to fix this engine side for next kag update :sunglasses:
