### ISSUE TITLE
Forced team change on juggernaut pickup

### ISSUE THREAD

**Issue by Vam-Jam** [TFlippy/kag_territorycontrol#14]
> Neutrals can become a team without their permission.
If a juggernaut on a faction grabs a neutral and then suicides, the neutral is converted to their team until they die.
This could actually be a gamebreaking aspect, due to the fact the Juggernaut can open doors easily and could theoretically grief. This is an issue as the "neutral juggernaut" cannot be kicked from the faction.

Don't change the team of the person your picking up until it comes to throwing them

From Gingerbeard#5773 on discord

**Comment by Gingerbeard5773** [comment]
This behavior does not happen in game as of the moment, so this can be closed.
