### ISSUE TITLE
Adding big bombs? Removing buildings books

### ISSUE THREAD

**Issue by HolySSSS** [TFlippy/kag_territorycontrol#146]
ABB, RBB
the best jack of all trades change, big bomb sized nerf

_This is absolutely not just a massive dig at mason because he campaigned to bring big bomb back the hardest
Definitely not_

**Comment by laikadoggirl** [comment]
Ye big bombs coming back will bring us back into the dark age of tc, where a fight is won simply carrying a backpack with three of them, so to even it out, neutrals can no longer build to even get said bombs, get fucked mason
