### ISSUE TITLE
Quality over Quantity

### ISSUE THREAD

**Issue by HolySSSS** [TFlippy/kag_territorycontrol#153]
The server currently has a low amount of players each day, max 15 players,
right now it is easy to capture the map as 1 faction and keep it that way
with quantity (+Half of the server players belong to 1 faction or there are too many faction bases)

Solution: temporarily add a limit to factions in number of members and their bases (3 members, 2 bases is the best option rn)
We can also keep the limit (_forever_) by making it adaptive to the amount of players but it can be figured out later
It will be harder for factions to hold the map, thus making it more skill-based and interesting 
Faction leaders will also have to pick good members instead of getting a horde of newbies

And don't worry about the upkeep, you can still upgrade the bases.. like 4 times, thus +8 upkeep

**Comment by Gingerbeard5773** [comment]
I have been working on a cap system but am very hesitant to make a pull request for several reasons despite it being relatively ready, likely- what will happen is that I will push the contesting and traveling changes first and if those do not change the situation then this will become an option. Regardless, here is how my system works:
1) The faction has a minimum cap of 3 players. That means that no matter what, your faction will be able to sustain 3 players.
2) There is no cap requirement for any faction if the server's total player count is below 6. This is to let players have "sandboxing" time when there is not really enough players for a good war.
3) Faction cap is added to the minimum amount by calculating the amount of enemy faction players of all faction teams and then dividing it by 3. So if there was two factions with 3 players each the max faction cap would be 4. 

Heres another example situation-
blue has 2 players, red has 3 players and green has 4 players. The faction cap is 5 for blue and red however green will stay at 4 cap until blue or red adds more players.

Some debatable parts about the system:
- There will need to be a third party for factions to grow past 4 players
- It forces players to fight  (though this happens in almost all of the cap systems Ive thought of).
- Factions can have 4+ players when no other factions exist, if they got cap from old factions but then those factions died out.

Known bugs:
- cap can be bypassed if a faction player goes to sleep, new player joins faction and then sleeper rejoins.

**Comment by HolySSSS** [comment]
There is no mention of limiting faction bases.

This is going to be considered or not? The benefits are making the game more skillbased + limiting megafactions the tool of blocking neutral spawns.

**Comment by HolySSSS** [comment]
Closing: not relevant anymore.
