### ISSUE TITLE
Little Small Tiny Things

### ISSUE THREAD

**Issue by HolySSSS** [TFlippy/kag_territorycontrol#161]
Campfires added into Misc category of build menu for builders & engineers.
Igniting things with campfires. Dynamite too.
Papers change the faction bases to **"NAME"** instead of "Camp/Stronghold/Citadel **"NAME"** ". Also everything else the same way.

This may expand later.

**Comment by HolySSSS** [comment]
Tavern and bandit hut option to turn off the light.
Anyone can turn on/off the light in the bandit hut.
Only the tavern owner can turn on/off the light (& music?) in the tavern.
**Note: this is a small buff for neutrals, so they could be more stealthy. Thanks to Dragon-RBI for the idea.**

**Comment by HolySSSS** [comment]
Ivan Statue should become less annoying. Make a cap on speed increase and lower volume.

**Comment by HolySSSS** [comment]
Neutral Peasants should get at least 50 (100 optimal) wood to give a chance to go through obstacles or build bridges across pits **as resupply at ruins**.

**Comment by HolySSSS** [comment]
Bazooka is a weapon to rival gauss rifle thanks to it's good accuracy and rockets. Backblast may balance it.
This will increase the importance of stationary rocket launchers (if we will ignore adding backblast to it) as well.

**Comment by Gingerbeard5773** [comment]
From @grand mason#5773 on discord
- Make lanterns collide with tables
- Make chairs collide with platforms

**Comment by Gingerbeard5773** [comment]
Drakon-RBI#7541
UPF crates and other inventory buttons should only be accessible/seen when overlapping or close

**Comment by Gingerbeard5773** [comment]
Projectiles such as howitzer shells and small rockets should have platform support and not collide with them unless facing against.

**Comment by HolySSSS** [comment]
Various things taken out of discord:

1 - Sticky bombs and mines. Basically Gregors but with different activation method.
2 - Kudzu plant. A bush that likes to grow very rapidly around and very, very slowly break stone. Like 3x slower than rain.
3 - "Make a better jetpack". Figure that out for me.
4 - Scrap destroyed vehicles for metal and other materials instead of just breaking them.
5 - Ingot (gold only?) blocks, meat blocks, mithril blocks and enriched as well. 
5.1 - Ingot blocks will let people pack 25 (50 or 100 as options) ingots into 1 block, meat blocks are just for decorative reasons, mithril and enriched blocks are basically passive area killers.

**Comment by Wunarg** [comment]
Sticky bombs and mines (to tiles at least) will be possible with the modification station im working on
Kudzu is a bit of a lag nightmare so it requires great care (though technicly possible)
-Where would kudzu come from?

**Comment by HolySSSS** [comment]
Where to get Kudzu: nursery.

**Comment by jammer312** [comment]
> Kudzu is a bit of a lag nightmare so it requires great care

Not really, just implement it the same way it is commonly implemented in ss13 (btw I'm pretty sure whoever suggested it seen it in ss13), i.e. have a list of active kudzu "patches" and each time you want it to grow just take several random "patches" out of that list and make them expand. Such "patch" becomes inactive (leaves that list) when it gets surrounded by other "patches" on all sides, and whenever any kudzu "patch" is destroyed it makes all surrounding "patches" active. That way no matter how many patches there are it always eats the same amount of processing time. Might want to change it a bit to make smaller bushes grow not as fast and make larger bushes grow not as slow.

> Where to get Kudzu: nursery.

Getting it as a random result from some horrible recipe in chem lab is more canonical

**Comment by HolySSSS** [comment]
Heavy Balance Idea: Remove the option to attach UPF Peacekeepers to vehicles of any kind.

**Comment by HolySSSS** [comment]
(Indian) Tea that removes drug effects from players instantly. Can be used as ammo for dart gun.

**Comment by xcs011** [comment]
> 
> 
> (Indian) Tea that removes drug effects from players instantly. Can be used as ammo for dart gun.

see #228

**Comment by HolySSSS** [comment]
Extendable barracade, a cheaper version of the bunker door that allows coverage for players.
Doesn't use the security system, it's length is 3 blocks.

**Comment by xcs011** [comment]
> 
> 
> Extendable barracade, a cheaper version of the bunker door that allows coverage for players.
> Doesn't use the security system, it's length is 3 blocks.

bro I literally said I would make this if someone sprites it why do you put them here

**Comment by xcs011** [comment]
> 
> 
> Heavy Balance Idea: Remove the option to attach UPF Peacekeepers to vehicles of any kind.

this is ehhhhhh it would be much better to just balance by setting a max ammo cap on the peacekeeper, to force them to land and reload, or a lower fuel cap/higher consumption on vehicles

**Comment by xcs011** [comment]
> 
> 
> Neutral Peasants should get at least 50 (100 optimal) wood to give a chance to go through obstacles or build bridges across pits **as resupply at ruins**.

Did anyone do this yet or nah

**Comment by HolySSSS** [comment]
> bro I literally said I would make this if someone sprites it why do you put them here

I do it for two reasons: keeping the ideas in check & letting people easily check all the ideas instead of going through discord.

**Comment by HolySSSS** [comment]
Security system overhaul possibility (logic, linking more entities, turning off turrets and siren and possibly more).

**Comment by HolySSSS** [comment]
Security System Overhaul 2.0:
Remote Control instead of the security station, this removes the need for "logic".
Linking more entities, turning off turrets & zappers, etc.

**Comment by HolySSSS** [comment]
Alloy ingots chemistry: Stick 2 ingots into the lab, add methane or something different to make high pressure with heat, react the ingots into an alloy. These alloy ingots can be used as recipes for lategame weapons like ROFL, dart gun, acid thrower and tools like mithril breeder. Not recommended, it makes the game more boring somewhat, but it will gatekeep the players from creating ROFLs or other stuff 10 minutes into the game.

Coal Mine resource rate depended on playercount of the server. The more players are on the server, the faster coal mines will dig new resources. The increase of the rate will be soft until 8 players (like 5%+ increase or so), then it goes more drastic (10%+ increase or more).

**Comment by charliehstreet** [comment]
I havent seen someone craft an ROFL and use it in a match in a while, much less craft one 10 minutes into the game.

**Comment by HolySSSS** [comment]
> I havent seen someone craft an ROFL and use it in a match in a while, much less craft one 10 minutes into the game.

Guess I'm too speedrunny then for everyone, lol. I did make 1 ROFL in 15 minutes + I also rushed acid, it is possible to start destroying the map 10 minutes into the game.
![20210411055425_1](https://user-images.githubusercontent.com/81934438/125201163-8b899500-e276-11eb-99f1-86d5e25f447a.jpg)

**Comment by xcs011** [comment]
> Alloy ingots chemistry: Stick 2 ingots into the lab, add methane or something different to make high pressure with heat, react the ingots into an alloy. These alloy ingots can be used as recipes for lategame weapons like ROFL, dart gun, acid thrower and tools like mithril breeder. Not recommended, it makes the game more boring somewhat, but it will gatekeep the players from creating ROFLs or other stuff 10 minutes into the game.
> 
> Coal Mine resource rate depended on playercount of the server. The more players are on the server, the faster coal mines will dig new resources. The increase of the rate will be soft until 8 players (like 5%+ increase or so), then it goes more drastic (10%+ increase or more).

Why dartgun doe that's kinda rarted

**Comment by HolySSSS** [comment]
> Why dartgun doe that's kinda rarted

Ye I agree

**Comment by HolySSSS** [comment]
Various things taken out of discord:

1) Laika - Big Fucking Glove that knockbacks people.
2) Laika (and pretty much everyone) - Armor & Gun overhaul.
3) Laika / Gingerbeard - Zeppelin for players. Better fix the teleporting glitch.
4) ??? - Acid not breaking dirt anymore.
5) Laika - Ghillie suit (camouflage into a bush!).

Laika's based??

**Comment by HolySSSS** [comment]
Thanks to everyone suggesting ideas throughout 2021. Most of this is not relevant anymore, so, closing.
Some ideas out of here got "bumped" in new issues.
