### ISSUE TITLE
goldyMap, again

### ISSUE THREAD

**Issue by GoldyXEN** [TFlippy/kag_territorycontrol#162]
made a map pls add
![Goldy_TC_Underhang](https://user-images.githubusercontent.com/59768455/115647606-baa20180-a32c-11eb-8198-d21bd4acd68d.png)
the black dot in the middle with hex value of 232323 is supposed to be a special biome for that map

tl:dr biome
a dark, flipped land, with no rain
but it wouldnt be really fun if it allways was dark
so, sometimes, a background lighting flashes it with light

**Comment by laikadoggirl** [comment]
the underhang
