### ISSUE TITLE
goldyMap, page 2: shitpost no more

### ISSUE THREAD

**Issue by GoldyXEN** [TFlippy/kag_territorycontrol#163]
![Goldy_TC_Propesko_v2](https://user-images.githubusercontent.com/59768455/115983696-68badf00-a5ab-11eb-9ccd-317116d36ac8.png)
version on discord had incorrect chicken shop colors

![Goldy_TC_Netherland_v2](https://user-images.githubusercontent.com/59768455/115983714-825c2680-a5ab-11eb-9198-3eefd7a287c6.png)
sadly tc doesnt have shore biome
and pls rename basement_rem to basement_v2 k thx

**Comment by BanSandwitches** [comment]
me like
