### ISSUE TITLE
Bug fixing

### ISSUE THREAD

**Issue by Gingerbeard5773** [TFlippy/kag_territorycontrol#178]
This issue thread is for bugs of **any size**. If you have a bug that you would like fixed (or not) then place it in this thread for it to be recorded easier than on discord, and hopefully fixed faster. I will fix bugs in this thread until they stop coming in.

**Comment by Gingerbeard5773** [comment]
Xeno#2521
Molecular Fabricator is not available in alien wreckage.

**Comment by Gingerbeard5773** [comment]
grand mason#5773
'a column of glass blocks when above a glass background makes the bottom glass block purple on map'

Missing map texture caused by missing enum in maploader shid

**Comment by Gingerbeard5773** [comment]
grand mason #5773
'when multiple chickens are stuck in the same 2 by 2 box and fed a grain they all produce an eggs from only that one grain'

Why: grain collides with all chickens on same tick and so chickens all produce egg.

**Comment by Gingerbeard5773** [comment]
Concrete gives iron ore when being mined

Why: MaterialsFromTiles.as was messed with and some of the tiles got incorrectly set to certain material yield

**Comment by Gingerbeard5773** [comment]
Drakon-RBI#7541
'Hoob can put a grabbed player into a storage, affected player cannot play at all, only reconnecting helps (will spawn as a peasant after reconnecting)'

Why: tbd

**Comment by Gingerbeard5773** [comment]
When playing on the server, placing blocks will take 2x resources if the player continuously builds.

Why: Dumb shite related to the server not having correct internal timers, so it doesn't register that you already placed a block

**Comment by Gingerbeard5773** [comment]
On server, materials will display incorrect sprites for their amount.

Why: tbd

**Comment by Gingerbeard5773** [comment]
The faction join button will not be available to players even when conditions are supposed to be met.
Notes: Players report not being able to fix the bug even when rejoining or going next map.
Why: tbd, though I think I have an idea of why.

**Comment by Gingerbeard5773** [comment]
When using an exosuit, the 'ghost' sprite is incorrectly placed when facing left.

Why: the rotation point does not compensate for when the blob is facing a different direction.

**Comment by Gingerbeard5773** [comment]
Dead exosuit players will turn invisible and cannot be seen.

Why: The exosuit sprite tries to use frames that were never made when it is tagged as 'dead'.

**Comment by Jim-Smiff** [comment]
Issue where Fiks (heal) sound plays on loop until player reaches full health

Issue where the merchant shop hitbox covers up wooden blocks, which makes them unbreakable by players, and the only way to remove the wood blocks is by an explosion, shooting them out, or fire

The flame thrower flames can travel through doors, the raygun has the same issue. This is bad because both weapons are used by chickens, as as they can see through doors (I think they can), they can "shoot through them". And when chickens spawn to attack factions, they can lock down a base with mithril or fire.

**Comment by Gingerbeard5773** [comment]
Ogg file 'ShockMine_Explode' is missing, so chicken artillery shells emit no sound when exploding

Why: Accidental file removal in a past update.

**Comment by Gingerbeard5773** [comment]
Shotgun icon in gunshop is incorrectly cutoff

**Comment by Gingerbeard5773** [comment]
Putting stone buildings on top of wooden background does not update the wooden background. This is most commonly seen when upgrading from camp to fortress.

Why: tbd

**Comment by Gingerbeard5773** [comment]
Flashlight is not updating the position of the light.

Why: Gun update broke it due to angle changes

**Comment by Gingerbeard5773** [comment]
Barbedwire is painful to use.

Why: caused by manipulating barbedwire to drop without support, though breaking it in the process.

**Comment by Gingerbeard5773** [comment]
Jetpack effects don't work correctly on server

**Comment by Gingerbeard5773** [comment]
Sentry aimangle is messed up when attached to vehicles

**Comment by Gingerbeard5773** [comment]
Juggernaut throwing is buggy and players die immediately instead of being thrown.

Why: probably has to do with collision.

**Comment by ghost** [comment]
Neutral GasTanks doesn't have inventory accessible for neutrals

**Comment by ghost** [comment]
Equipment effects, drug effects, having altar followage, tavern spawnpoint all don't get synced on reconnecting

**Comment by ghost** [comment]
Dead trees and Mithril trees drop their mats when they get splashed with a water bucket even though they aren't taking damage

**Comment by ghost** [comment]
Remote storage is bugged in the following way: You can upgrade a Camp to a Stronghold with 150 Wood + 400 stone in the Camp (and 0 mats on yourself) because the Camp is counted twice as remote storage for its own upgrade menu. (same bug with all the other upgrade levels as well)

**Comment by ghost** [comment]
Remote storage is also bugged in the way where if you have, for example, 1 gold ingot in remote storage and 1 gold ingot in your player inventory and you go to a merchant and sell 1 gold ingot it will use both the gold ingots (but still only give 100 coins).

**Comment by ghost** [comment]
Knight no-anims

**Comment by ghost** [comment]
Class change to engineer, then use crak, then wait and transform in to a hobo, then class change to engineer again;  now try to use a drill on a blob and it won't deal damage (might affect other weapons too, I don't know)

Edit: I played around with it more; transforming into a hobo sets your teamnum to 255, therefore all the mapgenerated neutral blobs (trees, neutral doors at merchants, badgers) are "on your team" and using a drill or gun on them doesn't damage them.

**Comment by ghost** [comment]
Whether piglets are dead or alive doesn't get synced on connecting to the server (or the sprite doesn't get set), probably with other animals too etc.

**Comment by ghost** [comment]
Dead Cowos are invisible (probably same issue as exosuit)

**Comment by ghost** [comment]
Sharks and bisons stop moving (crash in brain script?) after a non-vanilla class (peasant, engineer etc) ride them.

**Comment by ghost** [comment]
Having ChickenMarket ownership doesn't give the 20% coins when someone buys lotteryticket or armoredcar. (fixing might actually make lotterytickets net positive though, not sure about the numbers)

**Comment by ghost** [comment]
When you first join a server your playerhead isn't the right one (it's always male default head)

**Comment by laikadoggirl** [comment]
> Knight no-anims

This is a certified bunnie moment.

**Comment by ghost** [comment]
Gramophone doesn't get synced on join

**Comment by ghost** [comment]
I think sometimes mithril gas decays on your client but not on the server (might be related to recent change that made mithhril gas decay faster); you still take damage from the gas that's there, but it's invisible/deleted on your screen.

**Comment by ghost** [comment]
> On server, materials will display incorrect sprites for their amount.

just wanted to say: I just noticed that only non-vanilla mats have the wrong icon; vanilla mats (wood etc.) have the correct ones every time I rejoin.

**Comment by ghost** [comment]
people with teamnum 100 can't go through faction door while the faction has lockdown disabled (line 9 of DoorCommon.as is `if (blob.getTeamNum() > 100 && this.getTeamNum() < 7)`)

**Comment by ghost** [comment]
Putting a hobo into a storage, then reconnecting causes the inventory to be kinda broken

https://user-images.githubusercontent.com/26771587/125894481-27d686bc-eca7-4229-9130-6f58bc230009.mp4

**Comment by ghost** [comment]
Sometimes traders have so many trades that the last few are outside the shop frame, for example here the trader has the weapon trades, but is missing the shotgun ammo trade (edit: and frag grenade trade) because there's no space in the shop frame:
![screen-21-07-16-07-27-10](https://user-images.githubusercontent.com/26771587/125896406-50254194-6737-418f-938d-bf6ffb76240d.png)

**Comment by ghost** [comment]
When you name (for example) a blue faction with a paper and the blue faction dies; and someone faction another blue faction and that blue faction will still have the name that you set.

**Comment by laikadoggirl** [comment]
> 
> 
> When you name (for example) a blue faction with a paper and the blue faction dies; and someone faction another blue faction and that blue faction will still have the name that you set.

I can fix this one, either later tonight or tomorrow, it should be easy enough

**Comment by laikadoggirl** [comment]
> 
> 
> Sometimes traders have so many trades that the last few are outside the shop frame, for example here the trader has the weapon trades, but is missing the shotgun ammo trade (edit: and frag grenade trade) because there's no space in the shop frame:
> ![screen-21-07-16-07-27-10](https://user-images.githubusercontent.com/26771587/125896406-50254194-6737-418f-938d-bf6ffb76240d.png)

Ill fix this one too, let me just go down the list and do an assorted fixes pr

**Comment by laikadoggirl** [comment]
Hell ill do most of this list dont worry chief

**Comment by laikadoggirl** [comment]
door issue is covered please remove

**Comment by laikadoggirl** [comment]
> 
> 
> Class change to engineer, then use crak, then wait and transform in to a hobo, then class change to engineer again; now try to use a drill on a blob and it won't deal damage (might affect other weapons too, I don't know)
> 
> Edit: I played around with it more; transforming into a hobo sets your teamnum to 255, therefore all the mapgenerated neutral blobs (trees, neutral doors at merchants, badgers) are "on your team" and using a drill or gun on them doesn't damage them.

Im just gonna steal neutral team code and make it set you to a random neutral team when you become a hobo

**Comment by TC-DarkSlayer** [comment]
@Wunarg 
![image](https://user-images.githubusercontent.com/68712994/126573650-3a92f067-7734-452d-92eb-9d4f4cc25486.png)

So I believe this bug could be fixed by checking isServer() not sure, but check MinableMats.as

**Comment by TC-DarkSlayer** [comment]
Happens when you hit one of the minable mats with something that's not drill, Hitters::builder, or dynamite

**Comment by Vam-Jam** [comment]
> @Wunarg
> ![image](https://user-images.githubusercontent.com/68712994/126573650-3a92f067-7734-452d-92eb-9d4f4cc25486.png)
> 
> So I believe this bug could be fixed by checking isServer() not sure, but check MinableMats.as

IMO you should ignore this, that warning is being removed next KAG update when ever that may be since its no longer important to KAG

If you want to fix it by all means

**Comment by Gingerbeard5773** [comment]
Any remaining bugs should be put into their own issue for clarity @Hobey @xcs011. Closing
