### ISSUE TITLE
removing the 4x bonus for induction is literally retarded

### ISSUE THREAD

**Issue by laikadoggirl** [TFlippy/kag_territorycontrol#186]
yall stupid

**Comment by laikadoggirl** [comment]
literally the only difference between it and auto forge would be the coal cost, and you would be taking away the only bonus of using the induction

**Comment by Wunarg** [comment]
before you go nuts at least ask us if there is any more to it, first up the idear is to reduce the modifier of both the induction smelter and the autoforge, either 1x and 2x or 1x and 1x, in the second case of course induction furnace would receive some sort of other benefit or bonus to make it still usefull

**Comment by laikadoggirl** [comment]
thats kinda hard with vamist being a pushover and bunnie hating me, but 
nerfing to 2x is ass because it is a shit trade off for requiring coal
1x and 1x I doubt there is something useful enough compared to it being able to produce more

**Comment by Gingerbeard5773** [comment]
Coal cost would scale

**Comment by laikadoggirl** [comment]
> Coal cost would scale

Coal cost is already 1x1 except for steel?

**Comment by Gingerbeard5773** [comment]
As of the moment it takes 2 coal for 4 iron ingots- so to scale we would just divide by half and we would have a correctly scaled coal cost.

**Comment by TC-DarkSlayer** [comment]
I believe that induction furnace should instead just be 2x slower than it already is, but keep its 4x yield or if you wanna compromise even more, 3x yield is fine. :kag_smile: 
I also think autofurnace should yield more coal:wood ratio. Currently at 1-3 coal per 20 wood. Should be 1-3 coal per 15 or 10 wood . 
I also know that it gives good amount of coal already with automatic tree farms but still.

**Comment by HolySSSS** [comment]
What are you doing? Why do you want to change a core feature of TC industry branch? We need MORE fun features, not downgrade to make painful rounds for everyone! You are doing a stupid thing that will make people in TC rage! Just don't!
![1570121451113](https://user-images.githubusercontent.com/81934438/120937027-b9c60300-c713-11eb-8e23-eb5f2f91f808.jpg)
