### ISSUE TITLE
Non-Player Characters — Enemies

### ISSUE THREAD

**Issue by HolySSSS** [TFlippy/kag_territorycontrol#227]
We will define NPC Enemies as things that have a *hostile behaviour to it's surroundings* and *abilities to harm and kill* in this issue. An NPC Enemy basically can be any entity: block, object, workshop even (lol!~).

Examples: Kudzu, Aliens (Scythers, Gas, Death Ray Bots, Centipedes), Chickens & Gulls, Protopopov plant, Bison, Mithril Beasts.

This issue can be expanded with suggestions for new types of NPC Enemies.

**Comment by HolySSSS** [comment]
UPF Zeppelins: Massive Zeppelins designed to transport UPF airborne forces airdropping into the battle. Flies around and parachutes NPC Chickens and Player Chickens as well. The idea was picked up by @Gingerbeard5773 first.

![latest](https://user-images.githubusercontent.com/81934438/124499351-82a44980-ddc6-11eb-85fe-c6c4a6d8d843.png)
A reference image from TFlippy.

**Comment by jammer312** [comment]
Better reference image
![image](https://user-images.githubusercontent.com/3525275/124507300-33feab80-ddd6-11eb-92b5-54f5d998ff7d.png)

**Comment by laikadoggirl** [comment]
> 
> 
> Better reference image
> ![image](https://user-images.githubusercontent.com/3525275/124507300-33feab80-ddd6-11eb-92b5-54f5d998ff7d.png)

Kirov reporting

**Comment by HolySSSS** [comment]
Closing: not relevant anymore.
