### ISSUE TITLE
Merchant, Chicken market, Witch hut, Oil pump have the same minimap icon

### ISSUE THREAD

**Issue by ghost** [TFlippy/kag_territorycontrol#252]

**Comment by laikadoggirl** [comment]
If someone can get the icons from skem again I can see what I can do

**Comment by laikadoggirl** [comment]
![image0](https://user-images.githubusercontent.com/20747078/130310046-6064202a-c1d3-4ec3-b354-1757bef101e8.jpg)
attaching this here so I have it later to actually do this

**Comment by laikadoggirl** [comment]
image needs work will do later

**Comment by laikadoggirl** [comment]
done in #273 you can close it now
