### ISSUE TITLE
TC Development Team - Vote Results

### ISSUE THREAD

**Issue by TC-DarkSlayer** [TFlippy/kag_territorycontrol#268]
The Votes has spoken
Induction Furnace - Yield Change :  the 4x Ingot Yield Winning by a huge landslide
4x : 2x : 3x
13 : 2 : 1
Decision: 4x Ingot Yield for Induction Furnace

Auto Forge - Yield Change : the 2x Ingot Yield Winning by a huge landslide
2x : 1x : 1.5x
10 : 2  : 1
Decision: 2x Ingot Yield for Auto Forge

Induction Furnace - Coal Cost: Remove Coal barely won,
Remove Coal vs Keep Current Cost
8 : 6
Decision: Change Coal Ratio to 1:1:2:4 (Proposed by Me, DarkSlayer) Requires Further Discussion

**Comment by laikadoggirl** [comment]
Nah go back to the classic, 0:0:3:4
