### ISSUE TITLE
Blueprints

### ISSUE THREAD

**Issue by laikadoggirl** [TFlippy/kag_territorycontrol#283]
Now that blueprints could be openly bought, I would suggest they dare made single use.

**Comment by laikadoggirl** [comment]
Its a little retarded to let anyone buy the ability to manufacture cruise missiles, rng atleast kept them somewhat rare

**Comment by laikadoggirl** [comment]
Id honestly rather library is removed, or chicken assembler nerfed, but this would keep them atleast somewhat less common

**Comment by TC-DarkSlayer** [comment]
> buys blueprint
> can no longer buy blueprint
> builds new library

**Comment by TC-DarkSlayer** [comment]
library is meant just to make it obtainable if there is no way to obtain it, that's why it's so expensive

**Comment by laikadoggirl** [comment]
> 
> 
> > buys blueprint
> > can no longer buy blueprint
> > builds new library

no not the library, I mean make the blueprints actually disapear on use 
that way they have to either rebuy it for a retarded sum, or suffer

**Comment by TC-DarkSlayer** [comment]
That sounds like a good idea, tho some people gonna say "so I just forgot how to make it? dark you dumbfuck"
then i'll be depressed

**Comment by laikadoggirl** [comment]
sorry github is retardedly layed out 
+lol

**Comment by laikadoggirl** [comment]
and you dont exactly memorize how to make a single unit capable of manufacturing everything between guns and cruise missiles

**Comment by TC-DarkSlayer** [comment]
then again blueprints dont just disappear after you use them irl
