### ISSUE TITLE
Drills not working!

### ISSUE THREAD

**Issue by DARK-DarkSlayer** [TFlippy/kag_territorycontrol#37]
Drills after the vanilla drill build, drills stopped working properly in TC, they only break blocks now, everything else, it can't break. Such things include the following: Doors, buildings(quarters, factionbases, chickencoops), trees, characters(players, chickens, pigs), tanks, etc. Anything that is an entity(non-transparent-solid blocks).

@TFlippy

**Comment by Vam-Jam** [comment]
This could probably be caused by the build level changes that happened for the engi class. I doubt vanilla would have done this

**Comment by HKGx** [comment]
@Vam-Jam 
drills stopped working properly after 3007 update iirc.

**Comment by DARK-DarkSlayer** [comment]
The update when drills had heat indicators iirc

**Comment by TFlippy** [comment]
Fixed a long time ago, forgot to close this.
