### ISSUE TITLE
TFlippy is not adding my awsome TC maps

### ISSUE THREAD

**Issue by GoldyXEN** [TFlippy/kag_territorycontrol#47]
Probably some kind of weird bug, i expect the fix soon.

Here are my maps so you dont have to look them up

Goldy_TC_ThomsMega_Smoll
![Goldy_TC_ThomasMega_Smoll](https://user-images.githubusercontent.com/59768455/77486940-148e7a00-6e42-11ea-99cb-cc13b92c49b0.png)

Goldy_TC_DoubleVision
![Goldy_TC_DoubleVision](https://user-images.githubusercontent.com/59768455/77486941-15271080-6e42-11ea-9cc9-797883930af0.png)

Goldy_TC_Propesko
![Goldy_TC_Propesko](https://user-images.githubusercontent.com/59768455/77486943-15271080-6e42-11ea-8aed-0f64301c425b.png)

Goldy_TC_Sewers
![Goldy_TC_Sewers](https://user-images.githubusercontent.com/59768455/79793275-f6d90580-8358-11ea-8b59-5099c4055e01.png)

Goldy_TC_Hollows
![Goldy_TC_Hollows](https://user-images.githubusercontent.com/59768455/79793254-e9238000-8358-11ea-836f-6c0679d1b474.png)

**Comment by Vam-Jam** [comment]
Merged
