### ISSUE TITLE
Preplaced lanterns are stupidly stronk

### ISSUE THREAD

**Issue by jammer312** [TFlippy/kag_territorycontrol#5]
Lanterns that are loaded with map (I suppose) don't respect gravity and can do a lot of collision damage before breaking. For example, flying spotter (triplane) that collides with such aerial lantern loses half it's hp on collision.

**Comment by Vam-Jam** [comment]
Its like that in vanilla kag, should be pretty easy to fix

**Comment by Vam-Jam** [comment]
This has been fixed in the new test build for KAG (soon to be released to the public build)
