### ISSUE TITLE
Triangles at certain angles have A LOT of bullet damage resistance.

### ISSUE THREAD

**Issue by BurninDreamer** [TFlippy/kag_territorycontrol#93]
So if you place a stone triangle at a certain angle and let's say an UPF scout shoots it, it may take damage properly OR be like iron doors and gunfire (iron doors are pog against gun)

**Comment by Gingerbeard5773** [comment]
Tested this in localhost awhile ago. Last I remember, shooting the hypotenuse side of the triangle negates all the damage (though I think that it damages the background tile instead).

**Comment by laikadoggirl** [comment]
This is literally just how slopes work, bullets ricochet off, and deal less damage, hence the concept of sloped armor

**Comment by Gingerbeard5773** [comment]
solved in gun update
