### ISSUE TITLE
Bombs in general.

### ISSUE THREAD

**Issue by BurninDreamer** [TFlippy/kag_territorycontrol#94]
Alright this pisses me out a lot.
So if you throw let's say a bunker buster at a certain angle and at a certain speed it has a chance (which depends on the angle and speed but looks like rng on sight) it may deal from 5% of it's block and player damage to 100% 
and it's really annoying when you are trying to bust a bunker with bunker busters or any other bombs really (yeah I know that most of the bombs deal 0 damage to dirt but it's a different case)
you may not damage the bunker at all. My solution to this is to make bomb explosions fixed, so if you are throwing a bunker buster at the angle so it goes a lot to the left/right it won't, but instead go at a fixed pattern, at a fixed angle of 90 degrees.

**Comment by BurninDreamer** [comment]
ah yeah bunker busters are mostly an example but they are affected a lot and since they are the new meta for bonking bases since big bombs died it's pretty important

**Comment by Gingerbeard5773** [comment]
If I understand your suggestion correctly- changing the bunker buster boom angle to a fixed angle would mean that players wouldn't be able to just chuck them at other players like they do. It would be a pretty serious nerf and the only way to really use them is from bombers or large heights. If you are looking for an example of what you would be changing to- look at the mithril bomb found from spaceships, as it uses the fixed 90 degrees method rather than the velocity angle method the bunker buster uses.

**Comment by laikadoggirl** [comment]
> 
> 
> If I understand your suggestion correctly- changing the bunker buster boom angle to a fixed angle would mean that players wouldn't be able to just chuck them at other players like they do. It would be a pretty serious nerf and the only way to really use them is from bombers or large heights. If you are looking for an example of what you would be changing to- look at the mithril bomb found from spaceships, as it uses the fixed 90 degrees method rather than the velocity angle method the bunker buster uses.

ok but is not throwing bunker busters, and forcing vehicle use, really that bad?

**Comment by asperger-sind** [comment]
> If I understand your suggestion correctly- changing the bunker buster boom angle to a fixed angle would mean that players wouldn't be able to just chuck them at other players like they do. It would be a pretty serious nerf and the only way to really use them is from bombers or large heights. If you are looking for an example of what you would be changing to- look at the mithril bomb found from spaceships, as it uses the fixed 90 degrees method rather than the velocity angle method the bunker buster uses.

I think it's actually going to be a buff since their damage will always be fixed and they wouldn't deal 0.3 damage in some cases.
I'd honestly do that for each and every single bomb like a rework since I think that stability for things like these is important.

**Comment by Gingerbeard5773** [comment]
Here is what it would look like to apply these changes.

https://user-images.githubusercontent.com/68350259/113466315-134e4080-93f8-11eb-8349-83cf0df5118b.mp4

The bomb's linear explosion (the explosions that come out from the bomb in the direction it faces) still depends on the velocity you throw it at.

https://user-images.githubusercontent.com/68350259/113466362-7049f680-93f8-11eb-8a7d-23237e694790.mp4

Angle is not always going to be 90 degrees. It is based on the angle of the blob itself, so you can still use methods like this to attack from the side (it will just be harder to setup).

**Comment by Gingerbeard5773** [comment]
... And here is a strange alternative idea. However, it is too inconsistent to actually use in game.

https://user-images.githubusercontent.com/68350259/113467086-ed2b9f00-93fd-11eb-8037-0fbaf7f567d2.mp4

**Comment by asperger-sind** [comment]
I amazingly love all 3 of the ideas and would love if that change would be applied to the game, the third idea in my opinion seems the most realistic.

**Comment by Gingerbeard5773** [comment]
Was resolved in #139 this issue can be closed

**Comment by Gingerbeard5773** [comment]
Was resolved pls close
