### ISSUE TITLE
Gauss rifle nerf/rework

### ISSUE THREAD

**Issue by BurninDreamer** [TFlippy/kag_territorycontrol#99]
The gauss rifle is currently one of the most powerful guns on the gun side of TC.
The gauss rifle is relatively easy to get and it's ammo is worth practically nothing with the current way the players get steel.
The cost of gauss rifle is currently:
750 Coins
15 Steel
10 Copper wires
50 Mithril
Which is relatively cheap if you can get the entire material base of this gun by making a factory and fueling it with 1k stone.

And as a even bigger problem to that, the gauss rifle deals a lot of damage, has a quick reload and can be inventory-loaded.

It deals as much damage as an AMR (maybe less or maybe more) but it doesn't even matter since an AMR can oneshot basically anything just like the gauss rifle which is:
Cheaper to make
You don't need to kill UPFs or open crates for it.
Deals enough damage to oneshot almost everything (Excuses: Juggernaut prob and shielded exosuit, also full on crackhead drugged all hp buffs hazmats can live)

I say the gauss rifle should deal 60% less damage, cost more and have a longer reload.

**Comment by Gingerbeard5773** [comment]
Hello. Ginger here. Many people have suggested nerfing the gauss for a while now. It was scheduled to be changed a few updates ago but it was forgotten. Since the gauss is very unbalanced for many players there were a few ideas thrown around
1. Change the ammo type.
One idea was to change the ammo from steel to something else. The biggest contender was mithril ingots.
2. Change the cost.
The idea that was closest to going into a PR was to add a gyromat into the recipe.

**Comment by BurninDreamer** [comment]
Jim of the Jim empire said that it might be great to make a new sort of ammo.
Gauss charge:
1 Steel and 5 batteries with a max stack of 5.

I'd say that the gyromat wouldn't be so great at the recipe since they are rare and it would sort of kill the gun's charm of being an AMR that can be crafted.

I would like to change the cost from 50 mithril to 10 mithril ingots.
Add 75 batteries to the cost of the gun instead of the copper wires.
25 Steel instead of 10.
And 1250 coins instead of 750.

I support the idea of mithril ingots being the ammo for the gauss but it's still a mess that a neutral with very limited inventory space can carry around 350 mithril ingots and use the gun constantly.
I'm saying that it is going to be better if the gun's ammo will be gauss charges since it will allow for more flexibility at nerfing the gun.

also pls make gauss charges cost 1 mithril ingot and 5 batteries that would be nice thnxbye

**Comment by Gingerbeard5773** [comment]
This issue was fulfilled in #126 pls close @Vam-Jam
